version: "3.8"

services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:base
    container_name: app_container
    command: py manage.py runserver 0.0.0.0:8000
